log_results: True
print_every: 100
report_image_every: 1000
lr: 0.0002
beta: 0.5
save_checkpoint: True
save_every: 3000
batch_size: 5
num_workers: 4
epochs: 10
print_freq: 100
dataloader:
  data_path: /datashare/
  image_size: 64
  target_type:
    - attr
#    - identity
#    - bbox
#    - landmarks
  batch_size: 128
  workers: 2

model:
  pretrain: False
  num_classes: 3

optimizer:
  optimizer_name: Adam
  learning_rate: 0.005
  weight_decay: 0.0006
  step_size: 3
  gamma: 0.1



